name: Release Tag
on:
  push:
    branches:
      - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract version name 
      uses: mathieudutour/github-tag-action@v5.5
      id: tag_version_name
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump iOS version
      if: ${{ env.VERSION_BUMP == 'true'}}
      run: cd ios && bundle install && bundle exec fastlane version_bump
      id: tag_version
    - name: Create a GitHub Release  
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.tag_version.outputs.version }} 
        release_name: AppStore_v${{ steps.tag_version.outputs.version }} 
